#pragma multiinclude

#ifndef FIRST_SYMBOL_VALUE
#define FIRST_SYMBOL_VALUE 1
#endif

#ifndef BUILD_NAMES
#  if !defined( NAME_ENUMERATION_DECLARED )
#    define FIRST_SYMNAME(name,control_type_name)    FIRST_SYMBOL = FIRST_SYMBOL_VALUE, name = FIRST_SYMBOL_VALUE
#    define SYMNAME(name,control_type_name)        , name
#    define SYMNAME_SKIP(prior, range, name,control_type_name)        , prior, name = prior+range

enum resource_enum {
#  endif
#endif
#if !defined( NAME_ENUMERATION_DECLARED ) || defined( BUILD_NAMES )
#undef BTN_OKAY
#undef BTN_CANCEL
FIRST_SYMNAME( BTN_OKAY, NORMAL_BUTTON_NAME )
SYMNAME(BTN_CANCEL,NORMAL_BUTTON_NAME)
SYMNAME( BTN_ABORT, NORMAL_BUTTON_NAME )
SYMNAME( EDT_X     , EDIT_FIELD_NAME )
SYMNAME( EDT_Y     , EDIT_FIELD_NAME )
SYMNAME( EDT_WIDTH , EDIT_FIELD_NAME )
SYMNAME( EDT_HEIGHT, EDIT_FIELD_NAME )
SYMNAME( EDT_CAPTION, EDIT_FIELD_NAME)
SYMNAME( EDT_ID     , EDIT_FIELD_NAME)
SYMNAME( EDT_IDNAME , EDIT_FIELD_NAME)
SYMNAME( LABEL_X    , STATIC_TEXT_NAME )
SYMNAME( LABEL_Y    , STATIC_TEXT_NAME)
SYMNAME( LABEL_WIDTH  , STATIC_TEXT_NAME)
SYMNAME( LABEL_HEIGHT , STATIC_TEXT_NAME)
SYMNAME( LABEL_CAPTION, STATIC_TEXT_NAME)
SYMNAME( LABEL_ID     , STATIC_TEXT_NAME)
SYMNAME( LISTBOX_IDS , LISTBOX_CONTROL_NAME  )


SYMNAME( SLD_GREENBAR    , SLIDER_CONTROL_NAME )
SYMNAME( PAL_COLORS      , "Color Matrix" )
SYMNAME( BTN_PRESET      , NORMAL_BUTTON_NAME ) // define a preset
SYMNAME( CHK_ALPHA       , RADIO_BUTTON_NAME  )
SYMNAME( CST_SHADE       , "Shade Well" )
SYMNAME( CST_ZOOM        , "Shade Well" )
SYMNAME( CST_SHADE_RED   , "Shade Well" )
SYMNAME( CST_SHADE_BLUE  , "Shade Well" )
SYMNAME( CST_SHADE_GREEN , "Shade Well" )
		SYMNAME_SKIP( BTN_PRESET_BASE, 64, BTN_PRESET_LAST, CUSTOM_BUTTON_NAME )
#endif
#ifndef BUILD_NAMES
#  if !defined( NAME_ENUMERATION_DECLARED )
#  define NAME_ENUMERATION_DECLARED
};
#  endif
#endif
#undef SYMNAME
#undef FIRST_SYMNAME
#undef SYMNAME_SKIP
#undef BUILD_NAMES
