#define NUMLINES (sizeof(storytext)/sizeof(char *))
TEXTCHAR *storytext[]={WIDE("")
,WIDE("     In the beginning there was The Void.  Contained in The Void was")
,WIDE("nothing.  Out of the nothingness there was born the Elf- Mister Y.  ")
,WIDE("Famished from his spontaneous creation his mind formed the mad thought,")
,WIDE("\'LET'S MAKE COOKIES!\'  Astouneded by the sudden appearance of a cookie,")
,WIDE("he sat down to ponder this creation.  Turning it over in his hands he")
,WIDE("realized that he himself was but a cookie.  The one difference he could")
,WIDE("find between the two was that he could manipulate the cookie, whereas it")
,WIDE("was merely subject to his whim.  After consuming that cookie, he created")
,WIDE("another.  Again, he found the cookie to be subject to only his whim.")
,WIDE("     A time passed... another thought occured to him- given that these")
,WIDE("cookies where easily made, he began to wonder what else a cookie could")
,WIDE("do and look like.  He created a cookie that spun of it's own accord, and")
,WIDE("when it was touched went spinning off into The Void, lost.  \'Now that")
,WIDE("was rather odd... I wonder why it did that,\' Mr. Y thought.  After")
,WIDE("expiramenting a little he found that cookies could be made, and put inside")
,WIDE("of other cookies, or surround other cookies or be attached to another")
,WIDE("cookie.")
,WIDE("     Another time passed... A great deal of pondering and thought occured.")
,WIDE("Some of the cookies the elf ate, but most began to form a tremendous")
,WIDE("framework of intertwined cookies.  One day the Elf was wandering around")
,WIDE("inside of this grand structure and realized that he wanted to go back to")
,WIDE("The Void immidiately... so he created a cookie, climbed into it, and back")
,WIDE("out of it into the void.  \'That was intriguing...\' The next creation")
,WIDE("was a cookie which was both inside the structure and contained the")
,WIDE("structure.  The cookie was created successfully, but instantly the entire")
,WIDE("structure collapsed into itself finally dissappearing into nothingness.")
,WIDE("     So, enter... and create as you will...")
};
// $Log: story.h,v $
// Revision 1.2  2003/03/25 08:59:03  panther
// Added CVS logging
//
