

set ANDROID_SDK_ROOT=%ANDROID_HOME%/..
set ANDROID_NDK_VERSION=android-ndk-r9
set ANDROID_DIR=%ANDROID_SDK_ROOT%/%ANDROID_NDK_VERSION%
set PWD=%~dp0
set PWD=%PWD:\=/%

cmake -G "MinGW Makefiles" %PWD%cmake_all -D__ANDROID__=1 -DCMAKE_TOOLCHAIN_FILE=%PWD%a2_toolchain.txt -DANDROID_DIR=%ANDROID_DIR% -DANDROID_NDK_VERSION=%ANDROID_NDK_VERSION%


