/**
 *	@file    version.h
 *	@version 
 *
 *	Autogenerated version file.
 */
/*
    Copyright 2016 INSIDE Secure Corporation
*/
#ifndef _h_MATRIXSSL_VERSION
#define _h_MATRIXSSL_VERSION
#ifdef __cplusplus
extern "C" {
#endif

#define MATRIXSSL_VERSION      "3.8.3-OPEN"
#define MATRIXSSL_VERSION_MAJOR 3
#define MATRIXSSL_VERSION_MINOR 8
#define MATRIXSSL_VERSION_PATCH 3
#define MATRIXSSL_VERSION_CODE "OPEN"

#ifdef __cplusplus
}
#endif
#endif /* _h_MATRIXSSL_VERSION */

