.TH SNMP_PACKET_DUMP 3 "Mon Jan 25 23:11:52 1999"
.UC 4
.SH NAME
snmp_dump, snmp_dump_packet \- SNMP Network Packet Dumping Routines
.SH SYNOPSIS
.B cc
.RI "[ " "flag" " \|.\|.\|. ] " "file" " \|.\|.\|."
.B \-lsnmp
.RI "[ " "library" " \|.\|.\|. ]"
.LP
.B #include <sys/types.h>
.br
.B #include <snmp/snmp.h>
.LP
.BI "void snmp_dump_packet(int " "i");
.LP
.BI "void snmp_dump(unsigned char * " "Buf",
.BI "int " "BufLen",
.BI "char *" "How",
.BI "struct in_addr " "Who");
.SH DESCRIPTION
.B snmp_dump_packet(\|)
sets the boolean value for whether or not
.B snmp_dump(\|)
should do anything to the value of
.IR i .
.LP
.B snmp_dump(\|)
prints 
.I BufLen
bytes of
.IR Buf ,
with a header describing where it is going from/to.  The destination
machine is
.IR Who ,
and a description of how the data is moving is passed as
.IR How .
.LP
snmp_dump_packet(Buf, 15, "Sending", &from)
.LP
would result in a header that says
.LP
Sending 15 bytes <-> host.in.from:
.SH "RFCS"
Related RFCs: 1065, 1066, 1067
.br
Related SNMPv2 RFCs: 1901, 1902, 1902, 1904, 1905, 1906, 1907, 1908, 1909
.SH "RELATED URLS"
CMU Networking Group: http://www.net.cmu.edu/
.br
CMU SNMP Home Page: http://www.net.cmu.edu/projects/snmp
.SH "SEE ALSO"
.BR snmp_api (3),
.BR snmp_api_errors (3),
.BR snmp_client (3),
.BR snmp_coexistance (3),
.BR snmp_error (3),
.BR snmp_extra (3),
.BR snmp_mib (3),
.BR snmp_mibii (3),
.BR snmp_mini_client (3),
.BR snmp_msg (3),
.BR snmp_packet_dump (3),
.BR snmp_pdu (3),
.BR snmp_sess_api (3),
.BR snmp_vars (3),
.BR snmp_version_info (3),
.BR snmp_oid (5)
.BR snmp (3)
